# Cloudflare Pages configuration
# https://developers.cloudflare.com/pages/functions/wrangler-configuration/

name = "postrust-website"
compatibility_date = "2024-11-01"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = "./dist"
